blog/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('core.urls', 'core'), namespace='core')),
    path('posts/', include(('posts.urls', 'posts'), namespace='posts')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [path('__debug__/', include(debug_toolbar.urls))]
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.urls import path
from .feeds import LatestPostsFeed
from .views import (PostListView, PostDetailView, PostCreateView, PostUpdateView, AuthorPostListView,
                    AuditPostListView, PostDeleteView, ApprovePostView, ReplyDeleteView, ApproveReplyView)

urlpatterns = [
    path('', PostListView.as_view(), name='home'),
    path('create/', PostCreateView.as_view(), name='post_create'),
    path('my_posts/', AuthorPostListView.as_view(), name='author_post_list'),
    path('audit_posts/', AuditPostListView.as_view(), name='audit_posts'),
    path('<int:pk>/approve/', ApprovePostView.as_view(), name='approve_post'),
    path('<int:pk>/', PostDetailView.as_view(), name='post_detail'),
    path('<int:post_id>/replies/<int:reply_id>/approve/', ApproveReplyView.as_view(), name='reply_approve'),
    path('<int:post_id>/replies/<int:reply_id>/delete/', ReplyDeleteView.as_view(), name='reply_delete'),
    path('<int:pk>/edit/', PostUpdateView.as_view(), name='post_update'),
    path('<int:pk>/delete/', PostDeleteView.as_view(), name='post_delete'),
    path('latest/feed/', LatestPostsFeed(), name='post_feed'),
]

posts/models.py
import uuid
from django.contrib.auth import get_user_model
from django.db import models, transaction
from django.utils import timezone
from .managers import PostManager, ReplyManager
from .querysets import PostQuerySet, ReplyQuerySet

User = get_user_model()


class Reply(models.Model):
    name = models.CharField(verbose_name='Name', max_length=40)
    email = models.EmailField(verbose_name='Email', unique=False)
    content = models.CharField(verbose_name='Content', max_length=250)
    created_at = models.DateTimeField(verbose_name='Creation Date', auto_now_add=True)
    approved = models.BooleanField(verbose_name='Approved', default=False)
    marked_as_deleted = models.BooleanField(verbose_name='Marked as deleted', default=False)

    objects = ReplyManager.from_queryset(ReplyQuerySet)()

    def approve(self):
        self.approved = True
        self.save()

    def delete(self):
        self.marked_as_deleted = True
        self.save()
        return

    class Meta:
        verbose_name = 'Reply'
        verbose_name_plural = 'Replies'
        ordering = ['-created_at', '-approved']


def post_thumbnails_dir_path(instance, filename):
    """
    Function that creates a unique file name for each post thumbnail and returns the upload path.
    :param instance:
    :param filename:
    :return:
    """
    today = timezone.now()
    return 'thumbnails/{author}/{date}/{uniqueid}-{filename}'.format(
        author=instance.author,
        date=today.strftime("%Y/%m/%d"),
        uniqueid=uuid.uuid4(),
        filename=filename
    )


class Post(models.Model):
    thumbnail = models.FileField(verbose_name='Thumbnail', upload_to=post_thumbnails_dir_path, blank=True, null=True)
    title = models.CharField(verbose_name='Title', max_length=50)
    author = models.ForeignKey(verbose_name='Author', to=User, related_name='posts', on_delete=models.CASCADE, null=True)
    content = models.TextField(verbose_name='Content')
    replies = models.ManyToManyField(verbose_name='Replies', to=Reply, blank=True)
    created_at = models.DateTimeField(verbose_name='Creation Date', auto_now_add=True, blank=True)
    approved = models.BooleanField(default=False)
    marked_as_deleted = models.BooleanField(verbose_name='Deleted', default=False)

    @property
    def approved_replies(self):
        """
        Get approved replies.
        :return:
        """
        return self.replies.filter(approved=True, marked_as_deleted=False)

    objects = PostManager.from_queryset(PostQuerySet)()

    def __str__(self):
        return self.title

    def approve(self):
        self.approved = True
        self.save()

    def delete(self):
        # Ensure post deletion occurs inside a transaction, which means it has to delete both post and its replies or
        # don't delete any at all.
        with transaction.atomic():
            self.marked_as_deleted = True
            self.save()
            self.replies.delete()
        return

    class Meta:
        verbose_name = 'Post'
        verbose_name_plural = 'Posts'
        ordering = ['-created_at', '-approved']
        indexes = [
            models.Index(fields=['title'], name='idx_post_title'),
            models.Index(fields=['author'], name='idx_post_author'),
            models.Index(fields=['created_at'], name='idx_post_created_at'),
        ]

posts/forms.py
from django import forms

from posts.models import Reply, Post


class ReplyForm(forms.ModelForm):

    class Meta:
        model = Reply
        fields = ['name', 'email', 'content']
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control'}),
            'email': forms.EmailInput(attrs={'class': 'form-control'}),
            'content': forms.Textarea(attrs={'class': 'form-control'})
        }


class PostForm(forms.ModelForm):

    class Meta:
        model = Post
        fields = ['title', 'content', 'thumbnail']
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control'}),
            'content': forms.Textarea(attrs={'class': 'form-control'}),
            'thumbnail': forms.FileInput()
        }

posts/views.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import PermissionDenied
from django.shortcuts import redirect, get_object_or_404
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views import View
from django.views.generic import ListView, DetailView
from django.views.generic.edit import FormMixin, UpdateView, CreateView, DeleteView
from core.mixins import SuperUserRequiredMixin
from posts.forms import ReplyForm, PostForm
from posts.models import Post, Reply
from core.decorators import recaptcha_required


class AuditPostListView(LoginRequiredMixin, SuperUserRequiredMixin, ListView):
    model = Post
    template_name = 'posts/audit_posts.html'
    context_object_name = 'posts'

    def get_queryset(self):
        queryset = super().get_queryset()
        queryset = queryset.unpublished()
        queryset = queryset.order_by('-created_at')
        return queryset


class PostListView(ListView):
    model = Post
    template_name = 'posts/post_list.html'
    context_object_name = 'posts'

    def get_queryset(self):
        queryset = super().get_queryset()
        queryset = queryset.published()
        queryset = queryset.select_related('author')
        queryset = queryset.order_by('-created_at')
        return queryset


class AuthorPostListView(LoginRequiredMixin, ListView):
    model = Post
    template_name = 'posts/home.html'
    context_object_name = 'posts'

    def get_queryset(self):
        queryset = super().get_queryset()
        queryset = queryset.filter(author=self.request.user)
        queryset = queryset.published()
        queryset = queryset.order_by('-created_at')
        return queryset


class PostDetailView(FormMixin, DetailView):
    model = Post
    template_name = 'posts/post.html'
    form_class = ReplyForm

    def get_success_url(self):
        return reverse_lazy('posts:post_detail', kwargs={'pk': self.kwargs['pk']})

    def form_valid(self, form):
        reply = form.save(commit=False)
        post = self.get_object()
        reply.save()
        post.replies.add(reply)
        messages.info(self.request, message='Your reply must be approved before it can be displayed.')
        return redirect(self.get_success_url())

    def form_invalid(self, form):
        return self.render_to_response(self.get_context_data(form=form))

    @method_decorator(recaptcha_required)
    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        form = self.get_form()
        if form.is_valid() and request.recaptcha_is_valid:
            return self.form_valid(form)
        else:
            return self.form_invalid(form)


class PostCreateView(LoginRequiredMixin, CreateView):
    model = Post
    template_name = 'posts/post_form.html'
    form_class = PostForm

    def get_success_url(self):
        return reverse_lazy('posts:home')

    def form_valid(self, form):
        post = form.save(commit=False)
        post.author = self.request.user
        post.save()
        messages.info(self.request, message='Your post must be approved before it can be displayed.')
        return redirect(self.get_success_url())


class PostUpdateView(LoginRequiredMixin, UpdateView):
    model = Post
    template_name = 'posts/post_form.html'
    form_class = PostForm

    def get_success_url(self):
        return reverse_lazy('posts:post_detail', kwargs={'pk': self.kwargs['pk']})

    def get_object(self, queryset=None):
        obj = super().get_object()
        if not self.request.user.is_superuser:
            if not obj.author == self.request.user:
                raise PermissionDenied
        return obj


class PostDeleteView(LoginRequiredMixin, DeleteView):
    model = Post
    success_url = reverse_lazy('posts:author_post_list')

    def get_object(self, queryset=None):
        obj = super().get_object()
        if not self.request.user.is_superuser:
            if not obj.author == self.request.user:
                raise PermissionDenied
        return obj

    def get(self, request, *args, **kwargs):
        return super().delete(request, *args, **kwargs)


class ReplyDeleteView(LoginRequiredMixin, DeleteView):
    model = Reply

    def get_success_url(self):
        return reverse_lazy('posts:post_detail', kwargs={'pk': self.kwargs['post_id']})

    def get_object(self, queryset=None):
        post = get_object_or_404(Post, pk=self.kwargs['post_id'])
        if not self.request.user.is_superuser:
            if not self.request.user == post.author:
                raise PermissionDenied
        return post.replies.get(pk=self.kwargs['reply_id'])

    def get(self, request, *args, **kwargs):
        return super().delete(request, *args, **kwargs)


class ApprovePostView(LoginRequiredMixin, SuperUserRequiredMixin, View):

    def get_success_url(self):
        return reverse_lazy('posts:audit_posts')

    def get_object(self):
        return get_object_or_404(Post, pk=self.kwargs['pk'])

    def get(self, request, *args, **kwargs):
        post = self.get_object()
        post.approve()
        return redirect(self.get_success_url())


class ApproveReplyView(LoginRequiredMixin, View):

    def get_success_url(self):
        return reverse_lazy('posts:post_detail', kwargs={'pk': self.kwargs['post_id']})

    def get_object(self, queryset=None):
        post = get_object_or_404(Post, pk=self.kwargs['post_id'])
        if not self.request.user.is_superuser:
            if not self.request.user == post.author:
                raise PermissionDenied
        return post.replies.get(pk=self.kwargs['reply_id'])

    def get(self, request, *args, **kwargs):
        reply = self.get_object()
        reply.approve()
        return redirect(self.get_success_url())

templates/posts/audit_posts.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
    <h4>Posts waiting for approval</h4>
    {% if messages %}
    {% for message in messages %}
    <div class="alert alert-{{ message.tags}}" role="alert">
        {{ message }}
    </div>
    {% endfor %}
    {% endif %}
    {% for post in posts %}
    <div class="card mb-3" >
        <div class="row no-gutters">
            <div class="col-md-4">
                <img width="200" height="200" src="{% if post.thumbnail %}{{ post.thumbnail.url }}{% else %}https://via.placeholder.com/200{% endif %}" class="card-img" alt="{{ post.title }}">
            </div>
            <div class="col-md-8">
                <div class="card-body">
                    <h5 class="card-title">{{ post.title }}</h5>
                    <p class="card-text">{{ post.content|truncatechars:300 }}</p>
                    <p class="card-text">
                        <small class="text-muted">By: {{ post.author.username }} at {{ post.created_at|date:"m/d/Y H:i" }}</small>
                        &nbsp;
                        {% with reply_count=post.replies.count %}
                        <span class="badge badge-primary">{{ reply_count }} Repl{{ reply_count|pluralize:"y,ies" }}</span>
                        {% endwith %}
                        <span class="float-right">
                            <a href="{% url 'posts:approve_post' post.pk %}">Approve</a>
                            {% if request.user.is_superuser or request.user == post.author %}
                            |
                            <a href="{% url 'posts:post_delete' post.pk %}">Delete</a>
                            {% endif %}
                        </span>
                    </p>
                </div>
            </div>
        </div>
    </div>
    {% empty %}
    <p>There are no posts</p>
    {% endfor %}
</div>
{% endblock %}

templates/posts/post.html
{% extends 'base.html' %}
{% block head_content %}
<script src="https://www.google.com/recaptcha/api.js" async defer></script>
{% endblock %}

{% block content %}
{% with post=view.object %}
<div class="container">
    <div class="card" style="width: 50%;">
        <img class="card-img-top" width="200" height="200" src="{% if post.thumbnail %}{{ post.thumbnail.url }}{% else %}https://via.placeholder.com/200{% endif %}" alt="Card image cap">
        <div class="card-body">
            <h5 class="card-title">{{ post.title }}</h5>
            <p class="card-text">
                {{ post.content }}
            </p>
            <p class="text-muted">Author: {{ post.author.username }}<br>Publication: {{ post.created_at|date:"m/d/Y H:i" }}</p>
            <div class="float-right">
                {% if request.user.is_superuser or request.user == post.author %}
                <a href="{% url 'posts:post_update' post.pk %}">Edit</a>
                |
                <a href="{% url 'posts:post_delete' post.pk %}">Delete</a>
                {% endif %}
            </div>
        </div>
        <div class="card-footer">
            {% if messages %}
                {% for message in messages %}
                <div class="alert alert-{{ message.tags}}" role="alert">
                    {{ message }}
                </div>
                {% endfor %}
            {% endif %}
            <form method="post" action="{# url 'posts:reply_create' post_id=post.pk #}" style="padding: 10px;">
                {% csrf_token %}
                <div class="row">
                    &nbsp;<h6>Add a Reply</h6>
                </div>
                {% for field in form %}
                <div class="form-group row">
                    <label>{{ field.label }}</label>
                    {{ field }}
                    {% if field.errors %}<small style="color: red;">{{ field.errors }}</small>{% endif %}
                </div>
                {% endfor %}
                <div class="g-recaptcha" data-sitekey="6LerDskUAAAAAJtEoxJh4y2o0hWxqAB37xv_RccN"></div>
                <br/>
                <div class="row">
                    <button type="submit" class="btn btn-success">
                        Submit Reply
                    </button>
                </div>
            </form>
            <hr>
            {% with replies=post.replies.approved %}
                {% with reply_count=replies.count %}
                <h6>{{ reply_count }} Repl{{ reply_count|pluralize:"y,ies" }}</h6>
                {% endwith %}
                {% if replies %}
                    <br>
                    {% for reply in replies %}
                    <div style="border: 1px solid lightgrey; border-radius: 2px; padding: 10px; background: white; display: grid; margin-bottom: 10px;">
                        <div>
                            {{ reply.content }}
                            <br>
                            <p class="text-muted">{{ reply.name }} at {{ reply.created_at|date:"m/d/Y H:i" }}</p>
                            {% if request.user.is_superuser or request.user == post.author %}<a class="float-right" href="{% url 'posts:reply_delete' post_id=post.pk reply_id=reply.pk %}">Delete</a>{% endif %}

                        </div>
                    </div>
                    {% endfor %}
                {% endif %}
            {% endwith %}
            {% if request.user.is_superuser or request.user == post.author %}
                {% with unapproved_replies=post.replies.unapproved %}
                    {% if unapproved_replies %}
                    <hr>
                    {% with unapproved_replies_count=unapproved_replies.count %}
                    <h6>{{ unapproved_replies_count }} Repl{{ unapproved_replies_count|pluralize:"y,ies" }} waiting for approval.</h6>
                    {% endwith %}
                        <br>
                        {% for reply in unapproved_replies %}
                        <div style="border: 1px solid lightgrey; border-radius: 2px; padding: 10px; background: white; display: grid; margin-bottom: 10px;">
                            <div>
                                {{ reply.content }}
                                <br>
                                <p class="text-muted">{{ reply.name }} at {{ reply.created_at|date:"m/d/Y H:i" }}</p>
                                <span class="float-right">
                                    <a href="{% url 'posts:reply_approve' post_id=post.pk reply_id=reply.pk %}">Approve</a>
                                    |
                                    <a href="{% url 'posts:reply_delete' post_id=post.pk reply_id=reply.pk %}">Delete</a>
                                </span>

                            </div>
                        </div>
                        {% endfor %}
                    {% endif %}
                {% endwith %}
            {% endif %}
        </div>
    </div>
</div>
{% endwith %}
{% endblock %}

templates/posts/post_form.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <div class="card" style="padding: 10px;">
        <div class="card-title">
            {% if view.object %}
            <h5>Edit Post - <u>{{ view.object.title }}</u></h5>
            {% else %}
            <h5>Create new Post</h5>
            {% endif %}
        </div>
        <div class="card-body">
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="form-group row">
                    <label>{{ form.title.label }}</label>
                    {{ form.title }}
                </div>
                <div class="form-group row">
                    <label>{{ form.content.label }}</label>
                    {{ form.content }}
                </div>
                <div class="form-group row">
                    <label>{{ form.thumbnail.label }}</label>&nbsp;
                    {{ form.thumbnail }}
                </div>
                <div class="row">
                    <button type="submit" class="btn btn-success">
                        {% if view.object %}
                        Edit
                        {% else %}
                        Create
                        {% endif %}
                    </button>
                </div>
            </form>
        </div>

    </div>
</div>
{% endblock %}

templates/posts/post_list.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
    <h4>Posts</h4>
    {% if messages %}
    {% for message in messages %}
    <div class="alert alert-{{ message.tags}}" role="alert">
        {{ message }}
    </div>
    {% endfor %}
    {% endif %}
    {% for post in posts %}
    <div class="card mb-3" >
        <div class="row no-gutters">
            <div class="col-md-4">
                <img width="200" height="200" src="{% if post.thumbnail %}{{ post.thumbnail.url }}{% else %}https://via.placeholder.com/200{% endif %}" class="card-img" alt="{{ post.title }}">
            </div>
            <div class="col-md-8">
                <div class="card-body">
                    <h5 class="card-title">{{ post.title }}</h5>
                    <p class="card-text">{{ post.content|truncatechars:300 }}</p>
                    <p class="card-text">
                        <small class="text-muted">By: {{ post.author.username }} at {{ post.created_at|date:"m/d/Y H:i" }}</small>
                        &nbsp;
                        {% with approved_replies_count=post.replies.approved.count %}
                        <span class="badge badge-primary">{{ approved_replies_count }} Repl{{ approved_replies_count|pluralize:"y,ies" }}</span>
                        {% endwith %}
                        <span class="float-right">
                            <a class="" href="{% url 'posts:post_detail' post.pk %}">Details</a>
                            {% if request.user.is_superuser or request.user == post.author %}
                            |
                            <a class="" href="{% url 'posts:post_delete' post.pk %}">Delete</a>
                            {% endif %}
                        </span>
                    </p>
                </div>
            </div>
        </div>
    </div>
    {% empty %}
    <p>There are no posts</p>
    {% endfor %}
</div>
{% endblock %}