blog/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('core.urls', 'core'), namespace='core')),
    path('posts/', include(('posts.urls', 'posts'), namespace='posts')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [path('__debug__/', include(debug_toolbar.urls))]
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from .views import LoginView, LogoutView, SignupView, AuthorListView, AuthorUpdateView, AuthorDeleteView

urlpatterns = [
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('signup/', SignupView.as_view(), name='signup'),
    path('authors/', AuthorListView.as_view(), name='author_list'),
    path('authors/<int:pk>/edit/', AuthorUpdateView.as_view(), name='author_update'),
    path('authors/<int:pk>/delete/', AuthorDeleteView.as_view(), name='author_delete'),
]

posts/urls.py
from django.urls import path
from .feeds import LatestPostsFeed
from .views import (PostListView, PostDetailView, PostCreateView, PostUpdateView, AuthorPostListView,
                    AuditPostListView, PostDeleteView, ApprovePostView, ReplyDeleteView, ApproveReplyView)

urlpatterns = [
    path('', PostListView.as_view(), name='home'),
    path('create/', PostCreateView.as_view(), name='post_create'),
    path('my_posts/', AuthorPostListView.as_view(), name='author_post_list'),
    path('audit_posts/', AuditPostListView.as_view(), name='audit_posts'),
    path('<int:pk>/approve/', ApprovePostView.as_view(), name='approve_post'),
    path('<int:pk>/', PostDetailView.as_view(), name='post_detail'),
    path('<int:post_id>/replies/<int:reply_id>/approve/', ApproveReplyView.as_view(), name='reply_approve'),
    path('<int:post_id>/replies/<int:reply_id>/delete/', ReplyDeleteView.as_view(), name='reply_delete'),
    path('<int:pk>/edit/', PostUpdateView.as_view(), name='post_update'),
    path('<int:pk>/delete/', PostDeleteView.as_view(), name='post_delete'),
    path('latest/feed/', LatestPostsFeed(), name='post_feed'),
]

core/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import AuthenticationForm
from django import forms

User = get_user_model()


class LoginForm(AuthenticationForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['username'].widget = forms.TextInput(attrs={'class': 'form-control'})
        self.fields['password'].widget = forms.PasswordInput(attrs={'class': 'form-control'})


class SignupForm(forms.ModelForm):
    password_confirmation = forms.CharField(label='Password Confirmation', max_length=250,
                                            widget=forms.PasswordInput(attrs={'class': 'form-control'}))

    def clean_password_confirmation(self):
        password_confirmation = self.cleaned_data.get('password_confirmation')
        password = self.cleaned_data.get('password')
        if password != password_confirmation:
            raise forms.ValidationError("Password and Password Confirmation don't match.")
        return password_confirmation

    class Meta:
        model = User
        fields = ['username', 'email', 'password', 'password_confirmation']
        widgets = {
            'username': forms.TextInput(attrs={'class': 'form-control'}),
            'email': forms.EmailInput(attrs={'class': 'form-control'}),
            'password': forms.PasswordInput(attrs={'class': 'form-control'})
        }


class AuthorForm(forms.ModelForm):

    class Meta:
        model = User
        fields = ['username', 'email', 'is_active']
        widgets = {
            'username': forms.TextInput(attrs={'class': 'form-control'}),
            'email': forms.EmailInput(attrs={'class': 'form-control'}),
        }

core/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth import login
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView as AuthLoginView, LogoutView as AuthLogoutView
from django.core.exceptions import PermissionDenied
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.views import View
from django.views.generic import FormView, ListView, UpdateView
from .forms import LoginForm, SignupForm, AuthorForm
from .mixins import SuperUserRequiredMixin

User = get_user_model()


class LoginView(AuthLoginView):
    template_name = 'core/login.html'
    redirect_authenticated_user = True
    form_class = LoginForm


class LogoutView(AuthLogoutView):
    next_page = reverse_lazy('core:login')


class SignupView(FormView):
    template_name = 'core/signup.html'
    form_class = SignupForm
    success_url = reverse_lazy('posts:home')

    def form_valid(self, form):
        user = form.save(commit=False)
        user.set_password(user.password)
        user.save()
        login(self.request, user)
        return redirect(self.success_url)


class AuthorListView(LoginRequiredMixin, SuperUserRequiredMixin, ListView):
    model = User
    queryset = User.objects.all().order_by('-is_active', 'username')
    template_name = 'core/author_list.html'
    context_object_name = 'authors'


class AuthorUpdateView(LoginRequiredMixin, UpdateView):
    model = User
    template_name = 'core/author_form.html'
    form_class = AuthorForm
    success_url = reverse_lazy('core:author_list')

    def get_object(self, queryset=None):
        """
        Check if the request.user has permission to update the user object.
        :param queryset:
        :return:
        """
        user = super().get_object()
        if not self.request.user.is_superuser:
            if not user == self.request.user:
                # User from request is trying to update a different user, so deny the request.
                raise PermissionDenied
        return user

    def form_valid(self, form):
        user = form.save(commit=False)
        if not user.is_active:
            user.posts.delete()
        user.save()
        return redirect(self.success_url)


class AuthorDeleteView(LoginRequiredMixin, SuperUserRequiredMixin, View):

    def get_success_url(self):
        return reverse_lazy('core:author_list')

    def get(self, request, *args, **kwargs):
        user = self.get_object()
        user.is_active = False
        for post in user.posts.all():
            post.delete()
        user.save()
        return redirect(self.get_success_url())

templates/core/author_form.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <h5>
        {% if view.object %}
        Edit Author {{ view.object.username }}
        {% else %}
        Create new Author
        {% endif %}
    </h5>
    <form method="post">
        {% csrf_token %}
        {% if form.errors %}
        <div class="alert alert-danger" role="alert">
            {% for error in form.errors.values %}
            {{ error }}
            {% endfor %}
        </div>
        {% endif %}
        {% for field in form %}
        <div class="form-group row">
            {{ field.label }}
            {{ field }}
        </div>
        {% endfor %}
        <div class="col-md-6 offset-md-4">
            <button type="submit" class="btn btn-primary">
                Edit
            </button>
        </div>
    </form>
</div>
{% endblock %}

templates/core/author_list.html
{% extends 'base.html' %}
{% block content %}

<div class="container">
    <h5>Authors</h5>
    <table class="table">
        <thead>
        <tr>
            <th scope="col">ID</th>
            <th scope="col">Username</th>
            <th scope="col">Email</th>
            <th scope="col">Active</th>
            <th scope="col">Actions</th>
        </tr>
        </thead>
        <tbody>
        {% for author in authors %}
        <tr>
            <th scope="row">{{ author.pk }}</th>
            <td>{{ author.username }}</td>
            <td>{{ author.email }}</td>
            <td>{% if author.is_active %}Yes{% else %}No{% endif %}</td>
            <td>
                <a href="{% url 'core:author_update' author.pk %}">
                    <i class="fa fa-pencil"></i>
                </a>
                &nbsp;
                <a href="{% url 'core:author_delete' author.pk %}">
                    <i class="fa fa-times"></i>
                </a>
            </td>
        </tr>
        {% empty %}
        <h6>There are no authors.</h6>
        {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}

templates/core/login.html
{% extends 'base.html' %}
{% block content %}
<main class="login-form">
    <div class="cotainer">
        <div class="row justify-content-center">
            <div class="col-md-4">
                <div class="card">
                    <div class="card-header">Blog Project Login</div>
                    <div class="card-body">
                        <form method="post">
                            {% csrf_token %}
                            {% if form.errors %}
                            <div class="alert alert-danger" role="alert">
                                {% for error in form.errors.values %}
                                {{ error }}
                                {% endfor %}
                            </div>
                            {% endif %}
                            {% for field in form %}
                            <div class="form-group row">
                                {{ field.label }}
                                {{ field }}
                            </div>
                            {% endfor %}
                            <input type="hidden" name="next" value="{% url 'posts:home' %}">
                            <div class="col-md-6 offset-md-4">
                                <button type="submit" class="btn btn-primary">
                                    Login
                                </button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</main>
{% endblock %}

templates/core/signup.html
{% extends 'base.html' %}
{% block content %}
<main class="login-form">
    <div class="cotainer">
        <div class="row justify-content-center">
            <div class="col-md-4">
                <div class="card">
                    <div class="card-header">Blog Project Signup</div>
                    <div class="card-body">
                        <form method="post">
                            {% csrf_token %}
                            {% if form.errors %}
                            <div class="alert alert-danger" role="alert">
                                {% for error in form.errors.values %}
                                {{ error }}
                                {% endfor %}
                            </div>
                            {% endif %}
                            {% for field in form %}
                            <div class="form-group row">
                                {{ field.label }}
                                {{ field }}
                            </div>
                            {% endfor %}
                            <input type="hidden" name="next" value="{% url 'posts:home' %}">
                            <div class="col-md-6 offset-md-4">
                                <button type="submit" class="btn btn-primary">
                                    Signup
                                </button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</main>
{% endblock %}