blog/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('core.urls', 'core'), namespace='core')),
    path('posts/', include(('posts.urls', 'posts'), namespace='posts')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [path('__debug__/', include(debug_toolbar.urls))]
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from .views import LoginView, LogoutView, SignupView, AuthorListView, AuthorUpdateView, AuthorDeleteView

urlpatterns = [
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('signup/', SignupView.as_view(), name='signup'),
    path('authors/', AuthorListView.as_view(), name='author_list'),
    path('authors/<int:pk>/edit/', AuthorUpdateView.as_view(), name='author_update'),
    path('authors/<int:pk>/delete/', AuthorDeleteView.as_view(), name='author_delete'),
]

posts/urls.py
from django.urls import path
from .feeds import LatestPostsFeed
from .views import (PostListView, PostDetailView, PostCreateView, PostUpdateView, AuthorPostListView,
                    AuditPostListView, PostDeleteView, ApprovePostView, ReplyDeleteView, ApproveReplyView)

urlpatterns = [
    path('', PostListView.as_view(), name='home'),
    path('create/', PostCreateView.as_view(), name='post_create'),
    path('my_posts/', AuthorPostListView.as_view(), name='author_post_list'),
    path('audit_posts/', AuditPostListView.as_view(), name='audit_posts'),
    path('<int:pk>/approve/', ApprovePostView.as_view(), name='approve_post'),
    path('<int:pk>/', PostDetailView.as_view(), name='post_detail'),
    path('<int:post_id>/replies/<int:reply_id>/approve/', ApproveReplyView.as_view(), name='reply_approve'),
    path('<int:post_id>/replies/<int:reply_id>/delete/', ReplyDeleteView.as_view(), name='reply_delete'),
    path('<int:pk>/edit/', PostUpdateView.as_view(), name='post_update'),
    path('<int:pk>/delete/', PostDeleteView.as_view(), name='post_delete'),
    path('latest/feed/', LatestPostsFeed(), name='post_feed'),
]

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="pt-br">
<head>
    <title>Blog Project</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
          integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO"
          crossorigin="anonymous">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="{% static 'styles.css' %}">
    {% block head_content %}
    {% endblock %}
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="{% url 'posts:home' %}">BLOG</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'posts:home' %}">Home <span class="sr-only">(current)</span></a>
            </li>
            {% if request.user.is_authenticated %}
                {% if request.user.is_superuser %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'core:author_list' %}">Authors</a>
                </li>
                <li>
                    <a class="nav-link" href="{% url 'posts:audit_posts' %}">Audit Posts</a>
                </li>
                {% else %}
                <li>
                    <a href="{% url 'posts:author_post_list' %}" class="nav-link">My Posts</a>
                </li>
                {% endif %}
                <li>
                    <a href="{% url 'posts:post_create' %}" class="nav-link">New Post</a>
                </li>
            {% endif %}
            <li>
                <a class="nav-link" href="{% url 'posts:post_feed' %}">Feed</a>
            </li>
        </ul>
        <div class="right">
            {% if request.user.is_authenticated %}
            <span>Hello, {{ request.user.username }}!</span>
            &nbsp;|&nbsp;
            <a href="{% url 'core:logout' %}">Logout</a>
            {% else %}
            <a href="{% url 'core:signup' %}">Signup</a>
            &nbsp;|&nbsp;
            <a href="{% url 'core:login' %}">Login</a>
            {% endif %}
        </div>
    </div>
</nav>
<div style="margin-top: 20px;">
{% block content %}
{% endblock %}
</div>

<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
        integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"
        integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
        crossorigin="anonymous"></script>
</body>
</html>